financial_risk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^financial_risk/portal/', include(('portal.urls', 'portal'), namespace='portal')),
    url(r'^financial_risk/rcs_contributions/', include(('rcs_contributions.urls','rcs_contributions'), namespace='rcs_contributions' )),
    url(r'^financial_risk/rcs_optimization/', include(('rcs_optimization.urls', 'rcs_optimization'), namespace= 'rcs_optimization')),    
    url(r'^financial_risk/rcs_sensitivity/', include(('rcs_sensitivity.urls', 'rcs_sensitivity'), namespace= 'rcs_sensitivity')),    
    #url(r'^financial_risk/stress_sensitivity/', include(('stress_sensitivity.urls', 'stress_sensitivity'), namespace= 'stress_sensitivity')),    
    url(r'^', LoginView.as_view(template_name='portal/login.html'), name='login'),    
    url(r'^logout/', logout_then_login, name='logout'),  


]

portal/urls.py
from django.conf.urls import url, include
from portal.views import *





urlpatterns = [
    url(r'^$', index, name='index'), 
    #url(r'^$', login, {'template_name':'portal:login.html'}, name='login'),
    #url(r'^logout/', logout_then_login, name='logout'),  
] 

rcs_sensitivity/urls.py
from django.conf.urls import url
from rcs_sensitivity.views import *



urlpatterns = [
    url(r'^$', main, name='main'), 
    url(r'^success$', success, name='success'),    
    url(r'^results/(?P<id>\d+)/$', download_zip, name='results'),

] 

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	{% block extrastatic %}
<!-- Latest compiled and minified CSS -->
    <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      
      <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    
    <script type="text/javascript" src="{% static 'js/materialize.min.js'%}"></script>

     <style>
        .dropdown-content {
           overflow-y: visible;
        }

        .dropdown-content .dropdown-content {
           margin-left: 100%;
        }
        /*
        .right-triangle {
            float: right;            
        }
        .dropdown-content.nested {
           overflow-y: visible;
        }

        .dropdown-content .dropdown-content {
            margin-left: 100%;
        }
        .container {
            background: #eee;
            padding: 200px 100px;
            border-radius: 8px;
        }*/
    </style>

	{% endblock %}

	<title>{% block title %} Análisis de Riesgos {% endblock %}</title>

</head>

<body>
    <div>
    	{% block navbar %}

        
        <ul id="sub"  class="dropdown-content">
                    <li><a class="dropdown-trigger" href="#!" data-target="sub-2" data-hover="hover">One</a></li>
                    <li><a href="#!" >two</a></li>
        </ul>

        <ul id="sub-2"  class="dropdown-content">
                    <li><a href="#!" >one</a></li>
                    <li><a href="#!" >two</a></li>
        </ul>

        <ul id="conf"  class="dropdown-content">
                    <li><a href="{% url 'logout' %}" >Salir</a></li>
                    <li><a href="#!" >Contacto</a></li>
        </ul>
        

        <ul id="rcs" class="dropdown-content">                        
                    <li>
                    <a href="{% url 'rcs_contributions:main' %}" >Análisis</a>
            <!--<a class='dropdown-button' href="#" data-activates="sub-rcs" data-hover="hover" data-alignment="right">Sub<span >&#9656;</span></a>-->
                    </li>
                    <li><a href="{% url 'rcs_contributions:results' %}">Resultados</a></li>                        
        </ul>

        <ul id="sensitivity" class="dropdown-content">            
                    <li><a href="{% url 'rcs_sensitivity:main' %}" >Estres</a></li>
                    
        </ul>

        <ul id="optimization" class="dropdown-content">            
                    <li><a href="{% url 'rcs_optimization:main' %}" >Optimizado</a></li>
                    
        </ul>
        
        <ul id="opt" class="dropdown-content">            
                    <li>
                    <a class="dropdown-trigger" href="#!" data-target="sub" data-hover="hover" data-alignment="left">Opciones</a>
                    <!--<a href="{% url 'rcs_optimization:main' %}" >Portafolio</a>-->

                    </li>
                  
                    
        </ul>
        

        <nav>
        <div class="nav-wrapper teal">
                
               <!-- <a href="{% url 'portal:index' %}" class="brand-logo center" ><img  src="{% static 'img/risk.png' %}"></a>-->
            
            <ul id="nav-mobile2" class="left">
                <li><a class="dropdown-trigger" href="#!" data-target="rcs">RCS<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="sensitivity">Estres y Sensibilidad<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="optimization" >RCS Portafolio Optimizado<i class="material-icons right">arrow_drop_down</i></a></li>                
            </ul> 

            <ul id="nav-mobile" class="right">
                <li><a href="#" >Mis Resultados</a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="conf">Cuenta<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
            </div><!-- /.navbar-collapse -->


        </div><!-- /.container-fluid -->
        </nav>
    	{% endblock %}

    	{% block content %}
    	<h4> Bloque de contenido </h4>
    	{% endblock %}

    	{% block footer %}
    	{% endblock%}
    </div>

    	{% block extrajs %}
        <!-- Utils init select -->
        <script type="text/javascript" src="{% static 'js/utils.js'%}"></script>
    	{% endblock %}

   

</body>

</html>

templates/base/base2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Example nested dropdown</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
    <style>
        .right-triangle {
            float: right;
        }
        .dropdown-nested {
            overflow-y: visible;
        }
        .dropdown-content .dropdown-content {
            margin-left: 100%;
        }
        .container {
            background: #eee;
            padding: 200px 100px;
            border-radius: 8px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h3>Example nested dropdown</h3>
            </div>
        </div>
        
        <a class='dropdown-button btn' href='#' data-activates='dropdown1' data-beloworigin="true">Nested DropDown</a>

        <ul id='dropdown1' class='dropdown-content dropdown-nested'>
        <li><a class='dropdown-button' href='#' data-activates='dropdown2' data-hover="hover" data-alignment="left">one<span class="right-triangle">&#9656;</span></a></li>
            <li><a href="#!">two</a></li>
            <li><a href="#!">three</a></li>
        </ul>

        <ul id='dropdown2' class='dropdown-content dropdown-nested'>
            <li><a href="#!">one</a></li>
            <li><a class='dropdown-button' href="#" data-activates="dropdown3" data-hover="hover" data-alignment="left">two<span class="right-triangle">&#9656;</span></a></li>
            <li><a href="#!">three</a></li>
        </ul>

        <ul id='dropdown3' class='dropdown-content'>
            <li><a href="#!">three</a></li>
            <li><a href="#!">four</a></li>
            <li><a href="#!">five</a></li>
            <li><a href="#!">six</a></li>
        </ul>
    </div>
</body>
</html>